options:
  core-interface:
    type: string
    description: Host interface to use for the Core Network.
  core-interface-mtu-size:
    type: int
    description: |
      MTU for the core interface (1200 <= MTU <= 65535) in bytes.
      If not specified, Multus will use its default value (typically 1500).
  core-gateway-ip:
    type: string
    default: 192.168.250.1/24
    description: Gateway IP address in CIDR format to the Core Network.
  access-interface:
    type: string
    description: Host interface to use for the Access Network.
  access-interface-mtu-size:
    type: int
    description: |
      MTU for the core interface (1200 <= MTU <= 65535) in bytes.
      If not specified, Multus will use its default value (typically 1500).
  access-gateway-ip:
    type: string
    default: 192.168.252.1/24
    description: Gateway IP address in CIDR format to the Access Network.
  ran-interface:
    type: string
    description: Host interface to use for the RAN Network.
  ran-interface-mtu-size:
    type: int
    description: |
      MTU for the core interface (1200 <= MTU <= 65535) in bytes.
      If not specified, Multus will use its default value (typically 1500).
  ran-gateway-ip:
    type: string
    default: 192.168.251.1/24
    description: Gateway IP address in CIDR format to the RAN Network.
  ue-subnet:
    type: string
    default: 172.250.0.0/16
    description: Subnet used by User Equipments in CIDR format
  upf-core-ip:
    type: string
    default: 192.168.250.3
    description: UPF Core Network IP address
