name: Integration test

on:
  workflow_call:

jobs:
  integration-test:
    runs-on: [self-hosted, linux, X64, jammy, xlarge]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.1/stable
          provider: microk8s
          channel: 1.27-strict/stable
          microk8s-addons: "hostpath-storage"
      - name: Enable Multus addon
        continue-on-error: true
        run: |
          sudo microk8s addons repo add community https://github.com/canonical/microk8s-community-addons --reference feat/strict-fix-multus
          sudo microk8s enable multus
          sudo microk8s kubectl -n kube-system rollout status daemonset/kube-multus-ds
          sudo microk8s kubectl auth can-i create network-attachment-definitions
      - name: Run integration tests
        run: tox -vve integration
      - name: Collect logs
        if: failure()
        run: |
          snap logs microk8s.daemon-kubelite -n=all > $HOME/microk8s.logs
          microk8s.kubectl get mutatingwebhookconfigurations -oyaml --all-namespaces > $HOME/mutatingwebhookconfigurations.yaml
      - name: Archive microk8s logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: microk8s-logs
          path: "$HOME/microk8s.logs"
      - name: Archive mutatingwebhookconfigurations
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: mutatingwebhookconfigurations
          path: "$HOME/mutatingwebhookconfigurations.yaml"
      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: juju-crashdump
          path: juju-crashdump-*.tar.xz