name: Integration test

on:
  workflow_call:

env:
  NO_PROXY: "127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.canonical.com,.launchpad.net,.internal,.jujucharms.com,.nip.io,.svc"
  no_proxy: "127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.canonical.com,.launchpad.net,.internal,.jujucharms.com,.nip.io,.svc"

jobs:
  integration-test:
    runs-on: [self-hosted, linux, X64, jammy, xlarge]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Proxy
        run: |
          sudo sed -i "s#NO_PROXY.*#NO_PROXY=127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.canonical.com,.launchpad.net,.internal,.jujucharms.com,.nip.io,.svc#g" /etc/environment
          sudo sed -i "s#no_proxy.*#no_proxy=127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.canonical.com,.launchpad.net,.internal,.jujucharms.com,.nip.io,.svc#g" /etc/environment
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.1/stable
          provider: microk8s
          channel: 1.27-strict/stable
          microk8s-addons: "hostpath-storage"
      - name: Enable Multus addon
        continue-on-error: true
        run: |
          sudo microk8s addons repo add community https://github.com/canonical/microk8s-community-addons --reference feat/strict-fix-multus
          sudo microk8s enable multus
          sudo microk8s kubectl -n kube-system rollout status daemonset/kube-multus-ds
          sudo microk8s kubectl auth can-i create network-attachment-definitions
      - name: Run integration tests
        run: tox -vve integration
      - name: Collect logs
        if: always()
        run: |
          echo "============================================================================="
          env
          echo "============================================================================="
          sudo cat /etc/environment
          echo "============================================================================="
          
          sudo snap logs microk8s.daemon-kubelite -n=all
          sudo microk8s.kubectl get mutatingwebhookconfigurations -oyaml --all-namespaces
      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: juju-crashdump
          path: juju-crashdump-*.tar.xz